CREATE TABLE IF NOT EXISTS {users} (
  id BIGINT NOT NULL AUTO_INCREMENT,
  uuid CHAR(36) NOT NULL,
  player_name VARCHAR(32) NOT NULL,
  player_name_lower VARCHAR(32) NOT NULL,
  account_type VARCHAR(32) NOT NULL,
  password_enabled TINYINT(1) NOT NULL DEFAULT 1,
  password_plain VARCHAR(255) NULL,
  password_cipher VARCHAR(255) NULL,
  totp_enabled TINYINT(1) NOT NULL DEFAULT 0,
  totp_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  totp_secret VARCHAR(255) NULL,
  totp_pending_secret VARCHAR(255) NULL,
  register_invite_code VARCHAR(128) NULL,
  register_invite_id BIGINT NULL,
  locked TINYINT(1) NOT NULL DEFAULT 0,
  locked_reason VARCHAR(255) NULL,
  locked_by VARCHAR(32) NULL,
  locked_by_uuid CHAR(36) NULL,
  locked_at DATETIME(3) NULL,
  register_ip VARCHAR(45) NULL,
  last_login_ip VARCHAR(45) NULL,
  last_login_at DATETIME(3) NULL,
  last_server_name VARCHAR(64) NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_uuid (uuid),
  KEY idx_player_name_lower (player_name_lower),
  KEY idx_account_type (account_type),
  KEY idx_register_invite_code (register_invite_code),
  KEY idx_locked (locked),
  KEY idx_last_login_at (last_login_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
