CREATE TABLE IF NOT EXISTS {invite_codes} (
  id BIGINT NOT NULL AUTO_INCREMENT,
  code VARCHAR(128) NOT NULL,
  code_key VARCHAR(128) NOT NULL,
  batch_id VARCHAR(64) NULL,
  used TINYINT(1) NOT NULL DEFAULT 0,
  used_by_uuid CHAR(36) NULL,
  used_by_name VARCHAR(32) NULL,
  used_by_name_lower VARCHAR(32) NULL,
  used_account_type VARCHAR(32) NULL,
  used_ip VARCHAR(45) NULL,
  used_at DATETIME(3) NULL,
  created_by VARCHAR(32) NULL,
  created_by_uuid CHAR(36) NULL,
  created_at DATETIME(3) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  revoked TINYINT(1) NOT NULL DEFAULT 0,
  revoked_by VARCHAR(32) NULL,
  revoked_by_uuid CHAR(36) NULL,
  revoked_at DATETIME(3) NULL,
  note VARCHAR(255) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_code_key (code_key),
  KEY idx_used (used),
  KEY idx_revoked (revoked),
  KEY idx_expires_at (expires_at),
  KEY idx_used_by_uuid (used_by_uuid),
  KEY idx_batch_id (batch_id),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
